# Generated by Django 5.0 on 2024-01-07 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('start_from', models.CharField(choices=[('POP', 'POP'), ('CLIENT', 'Client'), ('JUNCTION', 'Junction'), ('GPON', 'Gpon')], max_length=100)),
                ('end_to', models.CharField(choices=[('POP', 'POP'), ('CLIENT', 'Client'), ('JUNCTION', 'Junction'), ('GPON', 'Gpon')], max_length=100)),
                ('number_of_cores', models.IntegerField()),
                ('length', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('polyline', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('POP', 'POP'), ('CLIENT', 'Client'), ('JUNCTION', 'Junction'), ('GPON', 'Gpon')], max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_number', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('assigned', models.BooleanField()),
                ('cable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.cable')),
                ('connected_cores', models.ManyToManyField(blank=True, to='map.core')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.marker')),
            ],
        ),
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('marker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map.marker')),
            ],
        ),
        migrations.CreateModel(
            name='Gpon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('splitter', models.IntegerField()),
                ('input_cable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.cable')),
                ('input_core', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_core', to='map.core')),
                ('output_cores', models.ManyToManyField(blank=True, related_name='output_cores', to='map.core')),
                ('marker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map.marker')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=100, null=True)),
                ('marker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map.marker')),
            ],
        ),
        migrations.AddField(
            model_name='cable',
            name='ending_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ending_point', to='map.marker'),
        ),
        migrations.AddField(
            model_name='cable',
            name='starting_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='starting_point', to='map.marker'),
        ),
        migrations.CreateModel(
            name='POP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('marker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map.marker')),
            ],
        ),
    ]
