# Generated by Django 5.0 on 2024-01-07 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_from', to='map.core')),
                ('core_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_to', to='map.core')),
            ],
        ),
    ]
