# Generated by Django 5.0 on 2024-01-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
