# Generated by Django 5.0 on 2024-01-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='connected_cores',
        ),
        migrations.RemoveField(
            model_name='gpon',
            name='output_cores',
        ),
        migrations.AlterField(
            model_name='cable',
            name='identifier',
            field=models.CharField(default='dd', max_length=100),
            preserve_default=False,
        ),
    ]
