# Generated by Django 5.0 on 2024-01-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_cable_polyline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='end_to',
            field=models.CharField(choices=[('POP', 'POP'), ('CLIENT', 'Client'), ('JUNCTION', 'Junction'), ('GPON', 'Gpon')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cable',
            name='start_from',
            field=models.CharField(choices=[('POP', 'POP'), ('CLIENT', 'Client'), ('JUNCTION', 'Junction'), ('GPON', 'Gpon')], max_length=100),
        ),
    ]
