# Generated by Django 5.0 on 2024-02-01 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_core_connected_cores_remove_gpon_output_cores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='ending_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_point', to='map.marker'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='starting_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_point', to='map.marker'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
