# Generated by Django 5.0 on 2024-02-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_cable_ending_point_alter_cable_starting_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='pop_type',
            field=models.CharField(choices=[('OLT', 'Olt'), ('Switch', 'Switch')], default='OLT', max_length=100),
            preserve_default=False,
        ),
    ]
